# # Generated by Selenium IDE
# # test_smokeTest.py

# import pytest
# import time
# import json
# from selenium import webdriver
# from selenium.webdriver.common.by import By
# from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.support import expected_conditions
# from selenium.webdriver.support.wait import WebDriverWait
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# class TestSmokeTest():
#   def setup_method(self, method):
#     self.driver = webdriver.Firefox()
#     self.vars = {}
  
#   def teardown_method(self, method):
#     self.driver.quit()
  
#   def test_adminPage(self):
#     self.driver.get("http://127.0.0.1:5500/teton/1.6/admin.html")
#     self.driver.set_window_size(748, 680)
#     self.driver.find_element(By.ID, "username").click()
#     elements = self.driver.find_elements(By.ID, "username")
#     assert len(elements) > 0
#     self.driver.find_element(By.ID, "username").send_keys("sanalucy")
#     self.driver.find_element(By.ID, "password").click()
#     self.driver.find_element(By.ID, "password").send_keys("hgh")
#     self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
  
#   def test_directoryPage(self):
#     self.driver.get("http://127.0.0.1:5500/teton/1.6/directory.html")
#     self.driver.set_window_size(748, 680)
#     self.driver.find_element(By.ID, "directory-grid").click()
#     assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
#     self.driver.find_element(By.ID, "directory-list").click()
#     assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
  
#   def test_homePage(self):
#     self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
#     self.driver.set_window_size(767, 680)
#     elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
#     assert len(elements) > 0
#     assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
#     assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
#     assert self.driver.find_element(By.CSS_SELECTOR, ".spotlight1 > h4").text == "Teton Elementary"
#     assert self.driver.find_element(By.CSS_SELECTOR, ".spotlight2 > h4").text == "Teton Post Office"
#     self.driver.find_element(By.LINK_TEXT, "Join Us!").click()
#     assert self.driver.find_element(By.CSS_SELECTOR, "section > h3").text == "Welcome to the Teton Chamber of Commerce Signup Wizard!"
#     assert self.driver.title == "Teton Idaho CoC"
  
#   def test_joinPage(self):
#     self.driver.get("http://127.0.0.1:5500/teton/1.6/join.html")
#     self.driver.set_window_size(748, 680)
#     elements = self.driver.find_elements(By.NAME, "fname")
#     assert len(elements) > 0
#     self.driver.find_element(By.NAME, "fname").send_keys("Alexander")
#     self.driver.find_element(By.NAME, "lname").click()
#     self.driver.find_element(By.NAME, "lname").send_keys("Cyril")
#     self.driver.find_element(By.NAME, "bizname").click()
#     self.driver.find_element(By.NAME, "bizname").send_keys("Ellux")
#     self.driver.find_element(By.NAME, "biztitle").click()
#     self.driver.find_element(By.NAME, "biztitle").send_keys("Manager")
#     self.driver.find_element(By.NAME, "submit").click()
#     self.driver.find_element(By.NAME, "email").click()
#     self.driver.find_element(By.NAME, "email").send_keys("sanchez.alexander.cyril@gmail.com")
#     self.driver.find_element(By.NAME, "cellphone").click()
#     self.driver.find_element(By.NAME, "cellphone").click()
#     self.driver.find_element(By.NAME, "cellphone").click()
#     self.driver.find_element(By.NAME, "cellphone").send_keys("208-458-4000")
  
















# Generated by Selenium IDE
# test_smokeTest.py

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.options import Options  # Changed for Firefox

class TestSmokeTest():
    def setup_method(self, method):
        options = Options()
        options.add_argument("--headless")  # Firefox headless mode
        self.driver = webdriver.Firefox(options=options)
        self.vars = {}
  
    def teardown_method(self, method):
        self.driver.quit()
  
    def test_adminPage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/admin.html")
        self.driver.set_window_size(748, 680)
        self.driver.find_element(By.ID, "username").click()
        elements = self.driver.find_elements(By.ID, "username")
        assert len(elements) > 0
        self.driver.find_element(By.ID, "username").send_keys("sanalucy")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("hgh")
        self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
  
    def test_directoryPage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/directory.html")
        self.driver.set_window_size(748, 680)
        self.driver.find_element(By.ID, "directory-grid").click()
        assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
        self.driver.find_element(By.ID, "directory-list").click()
        assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
  
    def test_homePage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
        self.driver.set_window_size(767, 680)
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
        assert len(elements) > 0
        assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
        assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
        assert self.driver.find_element(By.CSS_SELECTOR, ".spotlight1 > h4").text == "Teton Elementary"
        assert self.driver.find_element(By.CSS_SELECTOR, ".spotlight2 > h4").text == "Teton Post Office"
        self.driver.find_element(By.LINK_TEXT, "Join Us!").click()
        assert self.driver.find_element(By.CSS_SELECTOR, "section > h3").text == "Welcome to the Teton Chamber of Commerce Signup Wizard!"
        assert self.driver.title == "Teton Idaho CoC"
  
    def test_joinPage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/join.html")
        self.driver.set_window_size(748, 680)
        elements = self.driver.find_elements(By.NAME, "fname")
        assert len(elements) > 0
        self.driver.find_element(By.NAME, "fname").send_keys("Alexander")
        self.driver.find_element(By.NAME, "lname").click()
        self.driver.find_element(By.NAME, "lname").send_keys("Cyril")
        self.driver.find_element(By.NAME, "bizname").click()
        self.driver.find_element(By.NAME, "bizname").send_keys("Ellux")
        self.driver.find_element(By.NAME, "biztitle").click()
        self.driver.find_element(By.NAME, "biztitle").send_keys("Manager")
        self.driver.find_element(By.NAME, "submit").click()
        self.driver.find_element(By.NAME, "email").click()
        self.driver.find_element(By.NAME, "email").send_keys("sanchez.alexander.cyril@gmail.com")
        self.driver.find_element(By.NAME, "cellphone").click()
        self.driver.find_element(By.NAME, "cellphone").click()
        self.driver.find_element(By.NAME, "cellphone").click()
        self.driver.find_element(By.NAME, "cellphone").send_keys("208-458-4000")